services:
  - type: web
    name: YouTubeWatcher
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --port 80 --host 0.0.0.0 main:app"
    plan: free
    region: Oregon
