services:
  - type: web
    name: YouTubeWatcher
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:80 main:app"
    plan: free
    region: Oregon
